//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont

import 'package:flutter/material.dart' show IconData;

class Iconfont {
  static const String _family = 'iconfont';
  
  Iconfont._();
  
  static const IconData Iconshipin = IconData(0xe6f0, fontFamily: _family); // 视频
  static const IconData Iconbiaoqing = IconData(0xe6f1, fontFamily: _family); // 表情
  static const IconData Iconjinyong1 = IconData(0xe6f2, fontFamily: _family); // 禁用
  static const IconData Iconyuyin = IconData(0xe6f5, fontFamily: _family); // 语音
  static const IconData Icontupian = IconData(0xe6f7, fontFamily: _family); // 图片
}
